name: Daily File Check

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:
jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Check for Specific Files
      run: |
        chmod +x ./.github/scripts/check-files.sh
        ./.github/scripts/check-files.sh > files_to_check.txt

    - name: Send Email if Necessary
      if: steps.check-files.outputs.files != ''
      uses: dawidd6/action-send-mail@v2
      with:
        # Use a third-party action to send email; configure it as per the service's documentation
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Files to Revisit
        to: ${{ secrets.USER_EMAIL }}
        from: GitHub Actions
        body: file://files_to_check.txt
